"""Small-model harness image workbench.

The package is intentionally independent from ``src/``.  It is Koakumix's
image-generation boundary and delegates execution to an injected local
executor.
"""

from .assembly import (
    ASSEMBLY_SCHEMA,
    ASSET_INVALID,
    ASSET_ROOT_MISSING,
    ENV_ASSET_ROOT,
    ENV_DEVICE,
    ENV_EXECUTOR,
    ENV_MODEL_ID,
    EXECUTOR_DIFFUSERS,
    EXECUTOR_NOT_ENABLED,
    READY,
    RUNTIME_MISSING,
    ImageEngineAssembly,
    build_local_image_engine,
)
from .assets import ImageAssetRecord, ImageAssetStore
from .contracts import (
    GeneratedImage,
    ImageAdapter,
    ImageAdapterCapabilities,
    ImageAdapterError,
    ImageRequest,
    ImageRequestError,
)
from .diffusers_executor import (
    DEVICE_CHOICES,
    DTYPE_CHOICES,
    EXECUTOR_SCHEMA,
    DiffusersExecutorConfig,
    DiffusersImageExecutor,
    diffusers_available,
    executor_evidence,
)
from .editing import (
    CONTRACT_ONLY,
    EDIT_MODES,
    EDIT_MODE_SPECS,
    EDIT_REQUEST_SCHEMA,
    UNAVAILABLE,
    EditAvailability,
    EditModeSpec,
    ImageEditRequest,
    edit_capability_matrix,
    edit_mode_spec,
    resolve_edit_availability,
)
from .local_engine import LocalImageEngine, LocalImageEngineConfig
from .manifest import AssetManifestReport, validate_asset_manifest
from .refs import (
    IMAGE_REF_SCHEMA,
    MAX_CARD_CHARS,
    MAX_PROMPT_CHARS,
    MAX_REFS_PER_TURN,
    MULTIMODAL_CONTEXT_SCHEMA,
    SUPPORTED_MIME_TYPES,
    ImageAssetRef,
    ImageRefError,
    MultimodalContext,
    ThumbnailCard,
    build_multimodal_context,
    render_thumbnail_card,
)

__all__ = [
    "ASSEMBLY_SCHEMA",
    "ASSET_INVALID",
    "ASSET_ROOT_MISSING",
    "CONTRACT_ONLY",
    "DEVICE_CHOICES",
    "DTYPE_CHOICES",
    "EDIT_MODES",
    "EDIT_MODE_SPECS",
    "EDIT_REQUEST_SCHEMA",
    "ENV_ASSET_ROOT",
    "ENV_DEVICE",
    "ENV_EXECUTOR",
    "ENV_MODEL_ID",
    "EXECUTOR_DIFFUSERS",
    "EXECUTOR_NOT_ENABLED",
    "EXECUTOR_SCHEMA",
    "IMAGE_REF_SCHEMA",
    "MAX_CARD_CHARS",
    "MAX_PROMPT_CHARS",
    "MAX_REFS_PER_TURN",
    "MULTIMODAL_CONTEXT_SCHEMA",
    "READY",
    "RUNTIME_MISSING",
    "SUPPORTED_MIME_TYPES",
    "UNAVAILABLE",
    "AssetManifestReport",
    "DiffusersExecutorConfig",
    "DiffusersImageExecutor",
    "EditAvailability",
    "EditModeSpec",
    "GeneratedImage",
    "ImageAdapter",
    "ImageAdapterCapabilities",
    "ImageAdapterError",
    "ImageAssetRecord",
    "ImageAssetRef",
    "ImageAssetStore",
    "ImageEditRequest",
    "ImageEngineAssembly",
    "ImageRefError",
    "ImageRequest",
    "ImageRequestError",
    "LocalImageEngine",
    "LocalImageEngineConfig",
    "MultimodalContext",
    "ThumbnailCard",
    "build_local_image_engine",
    "build_multimodal_context",
    "diffusers_available",
    "edit_capability_matrix",
    "edit_mode_spec",
    "executor_evidence",
    "render_thumbnail_card",
    "resolve_edit_availability",
    "validate_asset_manifest",
]
